### ISSUE TITLE
xrange error

### ISSUE THREAD

**Issue by D82R** [SocraticBliss/ps4_env_decryptor#1]
When I try running the script, I am receiving the following error:

Traceback (most recent call last):
  File "ps4_env_decryptor.py", line 100, in <module>
    main(len(sys.argv), sys.argv)
  File "ps4_env_decryptor.py", line 94, in main
    data = aes_decrypt_cbc_cts(key, iv, message)
  File "ps4_env_decryptor.py", line 58, in aes_decrypt_cbc_cts
    output = ''.join(chr(ord(output[i]) ^ ord(iv[i])) for i in xrange(block_size))
NameError: name 'xrange' is not defined

**Comment by D82R** [comment]
This was because I was running python3. I have converted but I cannot seem to fix this error 

Traceback (most recent call last):
  File "mypy.py", line 96, in <module>
    main(len(sys.argv), sys.argv)
  File "mypy.py", line 90, in main
    data = aes_decrypt_cbc_cts(key, iv, message)
  File "mypy.py", line 54, in aes_decrypt_cbc_cts
    output = ''.join(chr(ord(output[i]) ^ ord(iv[i])) for i in range(block_size))
  File "mypy.py", line 54, in <genexpr>
    output = ''.join(chr(ord(output[i]) ^ ord(iv[i])) for i in range(block_size))
TypeError: ord() expected string of length 1, but int found

**Comment by SocraticBliss** [comment]
Sorry for taking so long to write back! I'll try making it python2&3 compatible :)
